@token = <access_token>

###

# 1. Create a new auction with a product
POST http://localhost:8081/auctions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "product": "Cook's iPhone 21",
  "minPrice": 1000
}
